#!/usr/bin/perl
# vim: ft=perl

use strict;
use Data::Dumper;

my $debug = 0;
#my $debug = 1;
my $basedir = $ENV{'HOME'} . '/.owir/';
my $file_type = shift @ARGV;
my $regex_file = $basedir . 'perlre/' . $file_type . '.perlre';

die 'no filter file found' if ! -r $regex_file;

open REGEX_FILE, $regex_file || die $!;

my @regexes = [];

while (<REGEX_FILE>)
{
  chomp;
  push(@regexes, qr/$_/);
}

print Dumper \@regexes if $debug;

while(<>)
{
  print if $debug;
  my $matched = 0;
  foreach my $regex (@regexes)
  {
    print $regex, "\n" if $debug;
    if ($_ =~ $regex)
    {
      print "matched\n" if $debug;
      $matched = 1;
      last;
    }
  }
  print unless $matched;
}
